package com.ListDecoding.tools.asn1ber_model;

public class Tag {
	//全部详单的所有接口字段
	public static final int IMSI                     = 101;
	public static final int MSISDN                   = 102;
	public static final int OTHER_PARTY              = 103;	//	对端号码
	public static final int NET_ACCOUNT              = 103;	//	上网账号
	public static final int DURATION                 = 105;	//	CALL_DURATION
	public static final int ESN_CODE                 = 106;
	public static final int MSC                      = 107;
	public static final int CALLING_LAC              = 108;
	public static final int CALLING_CELL             = 109;
	public static final int FORWARD_CAUSE            = 111;
	public static final int VISIT_AREA_CODE          = 112;	//	VISITAREACODE
	public static final int ROAMTYPE                 = 113;
	public static final int CALLED_CODE              = 114;
	public static final int CFEE                     = 117;	//	FIX_CDR_FEE
	public static final int LFEE                     = 118;
	public static final int FEE_ADD                  = 119;
	public static final int ACCT_ITEM_TYPE           = 120;
	public static final int CARRIER_CD               = 121;
	public static final int THIRD_PARTY              = 153;
	public static final int VPN_FLAG                 = 154;
	public static final int SELF_NUMBER              = 233;
	public static final int OPP_NUMBER               = 235;
	public static final int SP_CODE                  = 243;
	public static final int START_TIME               = 245;
	public static final int END_TIME                 = 246;	//	FIX_VDR_END_TIME	OTH_CDR_END_TIME	OTH_DDR_END_TIME	OTH_VDR_END_TIME
	public static final int TIMES                    = 254;
	public static final int RECV_BYTES               = 256;
	public static final int SEND_BYTES               = 257;
	public static final int PRODUCT_OFFER_ID         = 259;
	public static final int IFEE                     = 264;	//	INFO_FEE
	public static final int SPSRV_TYPE               = 267;
	public static final int CONTENT_CODE             = 278;
	public static final int CALL_TYPE                = 280;
//	public static final int END_TIME                 = 293;
	public static final int PSDN                     = 307;
	public static final int APNNI                    = 308;
	public static final int NAI_APNOI                = 309;
	public static final int HOME_AREA_CODE           = 315;
//	public static final int HOMEAREACODE             = 315;
	public static final int BASIC_FEE                = 322;
	public static final int TIMESTAMP                = 350;
	public static final int SMSCID                   = 353;
	public static final int CDRTYPE                  = 354;
	public static final int FEE                      = 356;
	public static final int CARRY_TYPE               = 432;
	public static final int BIZ_TYPE                 = 450;
	public static final int IMEI                     = 460;
	public static final int PRODUCT_ID               = 461;
	public static final int TRUNK_GROUPOUT           = 462;
	public static final int TRUNK_GROUPIN            = 463;
	public static final int CALLED_LAC               = 464;
	public static final int CALLED_CELL              = 465;
	public static final int CALLED_HOME_CODE         = 466;
	public static final int THIRD_HOME_CODE          = 467;
	public static final int THIRD_CODE               = 468;
	public static final int NAI_TYPE                 = 469;
	public static final int BSID                     = 470;
	public static final int PCF                      = 471;
	public static final int SERVICE_CODE             = 473;
	public static final int SERVICE_CODE_NAME        = 474;
	public static final int CONTENT_NAME             = 475;
	public static final int RESERVER1                = 483;
	public static final int RESERVER2                = 484;
	public static final int RESERVER3                = 485;
	public static final int RESERVER4                = 486;
	public static final int RESERVER5                = 487;
	public static final int PROV_OFFER_ID            = 488;
	public static final int PROV_RATEDATE            = 489;
	public static final int CDR_KEY                  = 490;
	public static final int PROV_BILLING_CYCLE_ID    = 491;
	public static final int RATE_TIMES               = 492;
	public static final int ACCT_ITEM_TYPE_A         = 493;
	public static final int ACCT_ITEM_TYPE_B         = 494;
	public static final int ACCT_ITEM_TYPE_C         = 495;
	public static final int FIX_CDR_ACCT_ITEM_TYPE_B = 495;
	public static final int BILLING_MODE             = 496;
	public static final int EVENT_TYPE               = 497;
	public static final int LONG_TYPE                = 498;
	public static final int SERVID                   = 2150;
	
}
